NewBuildSystem ;-) Changed to 1.6 Corrected LGTvMessageReader to use servlet instead of com.sun.xxxx httpserver Everything compiles, but one runtime problem still exists and prevents the further testing: instantiation of the servlet class fails
08:40:24.562 DEBUG o.o.b.l.internal.LgtvActivator[:33]- Lgtv binding has been started.
08:40:24.588 ERROR OSGi[:78]- Exception occurred while creating new instance of component Component[
        name = org.openhab.binding.lgtv.lginteraction
        activate = activate
        deactivate = deactivate
        modified =
        configuration-policy = optional
        factory = null
        autoenable = true
        immediate = true
        implementation = org.openhab.binding.lgtv.lginteraction.LgTvMessageReader
        state = Unsatisfied
        properties =
        serviceFactory = false
        serviceInterface = null
        references = {
                Reference[name = ItemUIRegistry, interface = org.openhab.ui.items.ItemUIRegistry, policy = dynamic, cardinality = 1..1, target = null, bind = setItemUIRegistry, unbind = unsetItemUIRegistry]
                Reference[name = HttpService, interface = org.osgi.service.http.HttpService, policy = dynamic, cardinality = 1..1, target = null, bind = setHttpService, unbind = unsetHttpService]
                Reference[name = ModelRepository, interface = org.openhab.model.core.ModelRepository, policy = static, cardinality = 1..1, target = null, bind = setModelRepository, unbind = unsetModelRepository]
        }
        located in bundle = org.openhab.binding.lgtv_1.6.0.201408261858 [222]
]
java.lang.InstantiationException: org.openhab.binding.lgtv.lginteraction.LgTvMessageReader
        at java.lang.Class.newInstance(Class.java:359)
        at org.eclipse.equinox.internal.ds.model.ServiceComponent.createInstance(ServiceComponent.java:493)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.createInstance(ServiceComponentProp.java:270)
        at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:331)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
        at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
        at org.eclipse.equinox.internal.ds.Resolver.buildNewlySatisfied(Resolver.java:473)
        at org.eclipse.equinox.internal.ds.Resolver.enableComponents(Resolver.java:217)
        at org.eclipse.equinox.internal.ds.SCRManager.performWork(SCRManager.java:816)
        at org.eclipse.equinox.internal.ds.SCRManager$QueuedJob.dispatch(SCRManager.java:783)
        at org.eclipse.equinox.internal.ds.WorkThread.run(WorkThread.java:89)
        at org.eclipse.equinox.internal.util.impl.tpt.threadpool.Executor.run(Executor.java:70)
08:40:24.589 DEBUG o.o.m.i.i.GenericItemProvider[:334]- Start processing binding configuration of Item 'LgTvPower (Type=SwitchItem, State=Uninitialized)' with 'LgtvGenericBindingProvider' reader.
08:40:24.606 DEBUG o.o.m.i.i.GenericItemProvider[:334]- Start processing binding configuration of Item 'LgTvMute (Type=SwitchItem, State=Uninitialized)' with 'LgtvGenericBindingProvider' reader.

-> i`ll open a question in openhab group